// packages/react/src/components/input.ts
import React, {
  forwardRef,
  useEffect,
  useImperativeHandle,
  useMemo,
  useRef,
  type ReactNode,
} from 'react';
import type { CoInput as CoInputElement, InputSize, InputType } from '@cobalt/components/input';
import '@cobalt/components/input';

export interface CoInputProps extends Omit<
  React.HTMLAttributes<CoInputElement>,
  'onBlur' | 'onFocus' | 'children'
> {
  label?: string;
  helperText?: string;
  errorText?: string;
  size?: InputSize;
  type?: InputType;
  value?: string;
  placeholder?: string;
  name?: string;
  autocomplete?: string;
  disabled?: boolean;
  invalid?: boolean;
  required?: boolean;
  readOnly?: boolean;
  children?: ReactNode;
  onCoFocus?: (event: Event) => void;
  onCoBlur?: (event: Event) => void;
}

export const CoInput = forwardRef<CoInputElement, CoInputProps>(function CoInput(
  {
    label = '',
    helperText = '',
    errorText = '',
    size = 'md',
    type = 'text',
    value = '',
    placeholder = '',
    name = '',
    autocomplete,
    disabled = false,
    invalid = false,
    required = false,
    readOnly = false,
    onCoFocus,
    onCoBlur,
    children,
    ...rest
  },
  forwardedRef,
) {
  const innerRef = useRef<CoInputElement>(null);

  useImperativeHandle(forwardedRef, () => innerRef.current as CoInputElement, []);

  const propertyBag = useMemo(
    () => ({
      label,
      helperText,
      errorText,
      size,
      type,
      value,
      placeholder,
      name,
      autocomplete,
      disabled,
      invalid,
      required,
      readOnly,
    }),
    [
      autocomplete,
      disabled,
      errorText,
      helperText,
      invalid,
      label,
      name,
      placeholder,
      readOnly,
      required,
      size,
      type,
      value,
    ],
  );

  useEffect(() => {
    const el = innerRef.current;
    if (!el) {
      return;
    }

    Object.assign(el, propertyBag);
  }, [propertyBag]);

  useEffect(() => {
    const el = innerRef.current;
    if (!el) {
      return;
    }

    const handleFocus = (event: Event) => {
      onCoFocus?.(event);
    };

    const handleBlur = (event: Event) => {
      onCoBlur?.(event);
    };

    if (onCoFocus) {
      el.addEventListener('co-focus', handleFocus);
    }

    if (onCoBlur) {
      el.addEventListener('co-blur', handleBlur);
    }

    return () => {
      if (onCoFocus) {
        el.removeEventListener('co-focus', handleFocus);
      }
      if (onCoBlur) {
        el.removeEventListener('co-blur', handleBlur);
      }
    };
  }, [onCoBlur, onCoFocus]);

  return React.createElement('co-input', { ref: innerRef, ...rest }, children);
});

// packages/angular/src/components/input.ts
import {
  Directive,
  ElementRef,
  EventEmitter,
  Input,
  Output,
  inject,
  type AfterViewInit,
  type OnChanges,
  type OnDestroy,
  type SimpleChanges,
} from '@angular/core';
import type { InputSize, InputType } from '@cobalt/components/input';
import '@cobalt/components/input';

@Directive({
  // eslint-disable-next-line @angular-eslint/directive-selector
  selector: 'co-input',
  standalone: true,
})
export class CoInput implements AfterViewInit, OnChanges, OnDestroy {
  @Input() label = '';
  @Input() helperText = '';
  @Input() errorText = '';
  @Input() size: InputSize = 'md';
  @Input() type: InputType = 'text';
  @Input() value = '';
  @Input() placeholder = '';
  @Input() name = '';
  @Input() autocomplete?: string;
  @Input() disabled = false;
  @Input() invalid = false;
  @Input() required = false;
  @Input() readOnly = false;

  @Output() readonly coFocus = new EventEmitter<CustomEvent>();
  @Output() readonly coBlur = new EventEmitter<CustomEvent>();

  private el = inject(ElementRef).nativeElement;
  private hasViewInitialized = false;

  ngAfterViewInit(): void {
    this.hasViewInitialized = true;
    this.syncToElement();
    this.el.addEventListener('co-focus', this.handleFocus);
    this.el.addEventListener('co-blur', this.handleBlur);
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (!this.hasViewInitialized) {
      return;
    }

    const currentValues = Object.fromEntries(
      Object.entries(changes).map(([key, change]) => [key, change.currentValue]),
    );
    this.syncToElement(currentValues);
  }

  ngOnDestroy(): void {
    this.el.removeEventListener('co-focus', this.handleFocus);
    this.el.removeEventListener('co-blur', this.handleBlur);
  }

  private syncToElement(overrides: Record<string, unknown> = {}): void {
    const apply = () => {
      const el = this.el as any;
      el.label = overrides.label ?? this.label;
      el.helperText = overrides.helperText ?? this.helperText;
      el.errorText = overrides.errorText ?? this.errorText;
      el.size = overrides.size ?? this.size;
      el.type = overrides.type ?? this.type;
      el.value = overrides.value ?? this.value;
      el.placeholder = overrides.placeholder ?? this.placeholder;
      el.name = overrides.name ?? this.name;
      el.disabled = overrides.disabled ?? this.disabled;
      el.invalid = overrides.invalid ?? this.invalid;
      el.required = overrides.required ?? this.required;
      el.readOnly = overrides.readOnly ?? this.readOnly;
      const autocomplete = overrides.autocomplete ?? this.autocomplete;
      if (autocomplete !== undefined) {
        el.autocomplete = autocomplete;
      }
    };

    if (customElements.get('co-input')) {
      apply();
      return;
    }

    void customElements.whenDefined('co-input').then(apply);
  }

  private handleFocus = (e: Event) => {
    this.coFocus.emit(e as CustomEvent);
  };

  private handleBlur = (e: Event) => {
    this.coBlur.emit(e as CustomEvent);
  };
}
